apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld-ingress
  annotations:
    kubernetes.io/ingress.class: contour
spec:
  rules:
    - host: helloworld.tanzudemo.frankcarta.com
      http:
        paths:
          - backend:
              service:
                name: helloworld
                port: 
                  number: 8080
            pathType: ImplementationSpecific
    - host: hello.helloworld.tanzudemo.frankcarta.com
      http:
        paths:
          - backend:
              service:
                name: helloworld
                port: 
                  number: 8080
            pathType: ImplementationSpecific
